keys:
  - &bsoudan age1q3p8k6wk4pd2kl46m43lq0q4vnvw6yp6ge29qnnmstkma6kghgxs6s9z7u
  - &core age1rfw22pyka4lp2n68g3gu5xe6v9x9mu4zmv0m6g977khnt65t7plsqdam9x
creation_rules:
  - path_regex: secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *bsoudan
      - *core

